### ISSUE TITLE
release tasks: march

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/cookiecutter-invenio-rdm#57]
In order to carry out the March release (v0.8.0) the following need to be addressed:

---

- [x] invenio-records-permission
    - [x] [Make readthedocs pick added docs](https://github.com/inveniosoftware/invenio-records-permissions/issues/42)

---

- [x] invenio-rdm-records
    - [x] [`resource_types` validation errors](https://github.com/inveniosoftware/invenio-rdm-records/issues/76)
    - [x] [`resource_types` customization](https://github.com/inveniosoftware/invenio-rdm-records/issues/5)
    - [x] [DOI bug](https://github.com/inveniosoftware/invenio-rdm-records/issues/81)
    - [x] [Rendering edtf bug](https://github.com/inveniosoftware/invenio-rdm-records/issues/80)
    - [x] [theme module structure](https://github.com/inveniosoftware/invenio-rdm-records/issues/63)
    - [x] Release v0.10.0

    - Would move to April: [`project_shortname`](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/45).

---

- [x] invenio-app-rdm
    - [x] Bump `invenio-rdm-records` if needed.
    - [x] [Merge styling improvements](https://github.com/inveniosoftware/invenio-app-rdm/pull/93)
    - [x] Release v0.7.0

---

- [x] Cookiecutter:
    -  ~~[ ] Upgrade to Invenio v3.3?~~
    -  [x] [Bump `invenio-rdm-records`and `invenio-app-rdm` version](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/60)
    -  [x] [Fix build and merge Dockerfile for deployment](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/56)
    -  [x] Create release branch (v0.7.0)

---

- [x] demo-inveniordm
    - [x] [Create demo site](https://github.com/inveniosoftware/demo-inveniordm/issues/6). Meeting Jose at 14 tomorrow to review the content of the front page (Styling).
    - [x] [Update logos](https://github.com/inveniosoftware/demo-inveniordm/issues/4). Can be part of the previous one. Reference: [Product Page](https://inveniosoftware.org/products/rdm/).
    - ~~[ ] [Upload docker image](https://github.com/inveniosoftware/demo-inveniordm/issues/7). Options described in [docs PR](https://github.com/inveniosoftware/docs-invenio-rdm/pull/39). Requires agreement on where to put it.~~
    - [x] [Automate docker image building and publish](https://github.com/inveniosoftware/demo-inveniordm/pull/8)
    - [x] [Secure instance](https://github.com/inveniosoftware/demo-inveniordm/issues/1)
    - [x] [Ensure record and file creation for authenticated users only](https://github.com/inveniosoftware/demo-inveniordm/issues/3)
    - ~~[ ] [Set up cronjob in OpenShift to wipe instance daily? weekly?](https://github.com/inveniosoftware/demo-inveniordm/issues/2)~~ --> Moved to April

---

- [x] helm-invenio
    - [x] [Shared volume](https://github.com/inveniosoftware/helm-invenio/pull/8) being reviewed by George, will be merged today. He is taking over the sidecar conatiner work.
    - [x] Requires decision on Dockerfile building

    - Would move to April: [Nginx config consolidation](https://github.com/inveniosoftware/helm-invenio/issues/6)

---

- [x] docs-invenio-rdm
    - [x] [Document usage of metadata extensions](https://github.com/inveniosoftware/docs-invenio-rdm/issues/38)
    - [x] [Document usage of custom `resource_types`](https://github.com/inveniosoftware/docs-invenio-rdm/issues/42)?
    - [x] [Helm usage improvements from Zach feedback](https://github.com/inveniosoftware/docs-invenio-rdm/pull/40) Pending review
    - [x] [Building images and registries](https://github.com/inveniosoftware/docs-invenio-rdm/pull/39) Reviewed by Zach already. Depends on cookicutter Dockerfile PR.
    - [x] [Benchmarking an instance](https://github.com/inveniosoftware/docs-invenio-rdm/pull/31) Requires agreement on the name. Benchmarking vs Verifying?
    - [x] [project name by month](https://github.com/inveniosoftware/docs-invenio-rdm/issues/24)

---

**Postponed, release didn't make it in time**
- ~~[ ] invenio-s3~~:
    - ~~[ ] Merge [big files fix](https://github.com/inveniosoftware/invenio-s3/pull/15)~~
    - ~~[ ] Release 1.0.3 (Part of above PR)~~
    - ~~No need to bump version in Cookicutter due to `invenio-s3 = "~=1.0.2"`.~~

    - Would leave for April: [Multiple endpoints config](https://github.com/inveniosoftware/invenio-s3/issues/14)

---

Extra: IIIF, SAML?
